### PR TITLE
Move UI to react

### PR DESCRIPTION
**Pull request by CopyDemon**
Based on the new design file, rewrite the UI with React:

[Link to design file](https://www.figma.com/file/ddrbVG8GYdoQ7WVbQm2pJA/Flowsheet-Visualizer-Mockups?type=design&node-id=0%3A1&mode=design&t=4gnyJI5Lq11j6rRT-1)

* The new UI should be broken down into components to ensure it's easy to maintain in the future.
* The new UI should retain the functionalities of the old UI.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
@CopyDemon is this currently working well enough for testing and generating new screenshots?

**Comment by CopyDemon** [comment]
> 

The label part needs styling. The other functions are working fine now. I will generate screenshot soon. Do you think I can generate a screen based on the existing screenshot on [idaes-ui.org](https://idaes-ui--23.org.readthedocs.build/en/23/fv.html#features)

**Comment by dangunter** [comment]
I know this is WIP, but I tried it and it doesn't work for me because it can't find "index.html"
The problem is here
```
# react app dir
_static_dir = _this_dir / "../../IDAES-UI/dist/"
_template_dir = _this_dir / "../../IDAES-UI/dist/"
```
There is no 'dist' subdirectory. Did you forget to add it to Git?
Is it built automatically? How will it get updated when you make changes?


Also the Python code is clunky (and always was). We should just refactor this into a little class, e.g.
```
class StaticFiles:
    """Locations of static files like templates and index.html
    """
    _this_dir = Path(__file__).parent.absolute()
    _index_file = "index.html"

    def __init__(self, old_site=False):
        self._old = old_site
        if not self._old:
            self._dist_dir = self._this_dir.parent.parent / "IDAES-UI" / "dist"

    @property
    def index_html(self):
        if self._old:
            return self._this_dir / "static" / self._index_file
        else:
            return self._dist_dir / self._index_file

    @property
    def static_dir(self):
        return self._this_dir / "static" if self._old else self._dist_dir
```

**Comment by CopyDemon** [comment]
> I know this is WIP, but I tried it and it doesn't work for me because it can't find "index.html" The problem is here
> 
> ```
> # react app dir
> _static_dir = _this_dir / "../../IDAES-UI/dist/"
> _template_dir = _this_dir / "../../IDAES-UI/dist/"
> ```
> 
> There is no 'dist' subdirectory. Did you forget to add it to Git? Is it built automatically? How will it get updated when you make changes?
> 
> Also the Python code is clunky (and always was). We should just refactor this into a little class, e.g.
> 
> ```
> class StaticFiles:
>     """Locations of static files like templates and index.html
>     """
>     _this_dir = Path(__file__).parent.absolute()
>     _index_file = "index.html"
> 
>     def __init__(self, old_site=False):
>         self._old = old_site
>         if not self._old:
>             self._dist_dir = self._this_dir.parent.parent / "IDAES-UI" / "dist"
> 
>     @property
>     def index_html(self):
>         if self._old:
>             return self._this_dir / "static" / self._index_file
>         else:
>             return self._dist_dir / self._index_file
> 
>     @property
>     def static_dir(self):
>         return self._this_dir / "static" if self._old else self._dist_dir
> ```

@dangunter has made some updates, and the `dist` folder should now be visible in `IDAES-UI/`. Currently, the port for the Python server is set to `random`. React reads the port from the `browser URL`. However, when you run React locally on `port 5173`, you'll need to either update the server port to 8099 or set up an environment variable pointing to port 8099.

**Comment by dangunter** [comment]
@CopyDemon for the port, we don't want to have a manual step in the workflow for starting the application (after the call to `visualize()`). Is that what you are saying there is now? Do you have a solution?

**Comment by CopyDemon** [comment]
> @CopyDemon for the port, we don't want to have a manual step in the workflow for starting the application (after the call to `visualize()`). Is that what you are saying there is now? Do you have a solution?

@dangunter just update the port remove manual step, the `.env.development` and `.env.production` to let react know to read port from different part.

`production:` python server serve dist folder with random port, when start UI in python server, UI can read port from URL.
`development`: vite start react from `port 5173`, the python server still start on `random port`, when python server start, it write shared_variable.json to react `/IDAES-UI/src/context/shared_variable.json`, react read environment variable `dev`, to get port from that json file not URL.

**Comment by dangunter** [comment]
The port thing doesn't work still. I think you're assuming directory locations. Also you shouldn't be writing to the file system outside of the ~/.idaes space

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[2], line 15
      9 # initialize the flowsheet as a square problem (dof=0)
     10 #vistut.initialize_model(model)
     11 
     12 # verify that there are zero degrees of freedom
     13 print(f"DOF = {degrees_of_freedom(model)}")
---> 15 model.fs.visualize("UI demo")

File ~\miniconda3\envs\idaes-ui\Lib\site-packages\idaes\core\base\flowsheet_model.py:280, in FlowsheetBlockData.visualize(self, model_name, **kwargs)
    266 def visualize(self, model_name, **kwargs):
    267     """
    268     Starts up a flask server that serializes the model and pops up a
    269     webpage with the visualization
   (...)
    278         None
    279     """
--> 280     UI().visualize(self, model_name, **kwargs)

File ~\src\idaes\shengpang\idaes-ui\idaes_ui\fv\fsvis.py:113, in visualize(flowsheet, name, save, load_from_saved, save_dir, save_time_interval, overwrite, browser, port, log_level, quiet, loop_forever)
    111 web_server = FlowsheetServer(port=port)
    112 web_server.add_setting("save_time_interval", save_time_interval)
--> 113 web_server.start()
    114 if not quiet:
    115     _log.info("Started visualization server")

File ~\src\idaes\shengpang\idaes-ui\idaes_ui\fv\model_server.py:95, in FlowsheetServer.start(self)
     93 IDAES_UI_path = './IDAES-UI/src/context/shared_variable.json'
     94 pathDic = [root, IDAES_UI_path]
---> 95 create_shared_JSON(self.port, "sample_visualization", pathDic)

File ~\src\idaes\shengpang\idaes-ui\idaes_ui\fv\model_server.py:488, in create_shared_JSON(current_port, flowsheet_name, filePathDic)
    486 for path in filePathDic:
    487     if not os.path.exists(path):
--> 488         with open(path, 'w') as f:
    489             json.dump({"url" : localhost_url, "port": current_port}, f)
    490     else:

FileNotFoundError: [Errno 2] No such file or directory: './IDAES-UI/src/context/shared_variable.json'
```

Also please follow the Google Python style guide for quotes, comments, etc.

**Comment by dangunter** [comment]
@CopyDemon I suggest instead of writing out ports, to just set the port in the example script to some known free port, and assume the same port for the Cypress config e.g.

in *idaes_ui/fv/example.py*
```
def fv_example():
    m = build_flowsheet()
    visualize(m.fs, "sample_visualization", port=49999)
    _log.info("Starting Flowsheet Visualizer")
    _log.info("Press Control-C to stop")
    try:
        while 1:
            time.sleep(1)
    except KeyboardInterrupt:
        _log.info("Flowsheet Visualizer stopped")
    return 0
```
... then use port 49999 in cypress.config.js

We can revisit a more general solution on the rewrite to FastAPI

**Comment by CopyDemon** [comment]
That is smart. In the prod mode, the python server serves build file, then js can read port from url. In dev mode, just use a fixed port in the example. Thanks!

**Comment by CopyDemon** [comment]
> @CopyDemon I suggest instead of writing out ports, to just set the port in the example script to some known free port, and assume the same port for the Cypress config e.g.
> 
> in *idaes_ui/fv/example.py*
> ```
> def fv_example():
>     m = build_flowsheet()
>     visualize(m.fs, "sample_visualization", port=49999)
>     _log.info("Starting Flowsheet Visualizer")
>     _log.info("Press Control-C to stop")
>     try:
>         while 1:
>             time.sleep(1)
>     except KeyboardInterrupt:
>         _log.info("Flowsheet Visualizer stopped")
>     return 0
> ```
> ... then use port 49999 in cypress.config.js
> 
> We can revisit a more general solution on the rewrite to FastAPI

That is smart. In the prod mode, the python server serves build file, then js can read port from url. In dev mode, just use a fixed port in the example. Thanks!

**Comment by dangunter** [comment]
It now works!
One minor thing: the IDAES logo in the upper-left corner is not found. Maybe the path needs to be relative to the source code not the run directory?

**Review by dangunter — COMMENTED** [review]
I see some places in paper.js where 'var' is used instead of 'let' or 'const'. Could you go through and see if you can replace those? There are very few places var is still needed I think.

**Review by dangunter — APPROVED** [review]
LGTM

**Pull request merged**
