### PR TITLE
Rework UI docs

### PR DESCRIPTION
**Pull request by dangunter**
Fixes EVERYTHING (about the docs at least)

Proposed changes:

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by CopyDemon** [comment]
@dangunter 
## To fix the cypress run fail: 
You can copy code from file `/idaes-ui/cypress/e2e/flowsheet_component.cy.js` from my [repo's branch add-diagnostics](https://github.com/CopyDemon/idaes-ui/blob/add-diagnostics/cypress/e2e/flowsheet_component.cy.js),

and to replace the file `/idaes-ui/cypress/e2e/flowsheet_component.cy.js` in your repo.

**Comment by dangunter** [comment]
@CopyDemon the change had no real effect, there is something else going on here

**Comment by lbianchi-lbl** [comment]
To get the screenshots, you can add a step after the Cypress one with [actions/upload-artifact](https://github.com/actions/upload-artifact?tab=readme-ov-file#usage) e.g.:

```yaml
- name: Upload screenshots
  if: ${{ always() }}
  uses: actions/upload-artifact@v4
  with:
    # use relevant options
```

**Comment by dangunter** [comment]
@CopyDemon and @lbianchi-lbl thanks for your help. I figured out what was wrong -- as usual, not where I was looking. There were some randomly named files under "assets" that needed to be added to the repo. I don't quite understand what these are for, why they need to be there, and why I had to add them in this PR, but anyways this fixes the issue. Plus, now we have screenshots :-) I reverted changes outside docs directory except addition of 'playwright' as a dependency.

**Review by CopyDemon — APPROVED** [review]

**Pull request merged**
